<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="NoXsd"
                  targetNamespace="some-namespace">
</wsdl:definitions>
