//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.30 at 03:47:44 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:helloWorld/sample/ibm/HelloWorld", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package helloworld.sample.ibm.helloworld;
